### ISSUE TITLE
Feature request non-blocking sandbox, ev. needs yielding engine

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [tau-prolog/sandbox#10]
TauProlog has a new interfaces:

> promiseQuery: queries a goal and returns a promise that is resolved 
when the goal loads successfully, or rejected when there is an error. It 
takes the same arguments as the query method.
http://tau-prolog.org/manual/promises-interface

The test case was a large limit and then:
```
longrunning :- 
    between(1,300,_),
    between(1,300,_),
    between(1,300,_),
    fail.
longrunning.
```
But I find that this sandbox here is blocking:

![Unbenannt](https://user-images.githubusercontent.com/95891213/152998836-89a6f59d-37b5-4919-b497-a2a86ef1af02.PNG)

http://tau-prolog.org/sandbox/

Is there another sandbox already online?

**Comment by jariazavalverde** [comment]
Tau Prolog is non-blocking, but as a National Department of Traffic slogan said: we can't drive for you. To release the browser you have two options: call an asynchronous predicate (such as `sleep/1`) that sleeps execution for a while, or use the inference limit that you can set in Tau Prolog. 

For instance, the following code doesn't freeze the browser: 

```prolog
:- use_module(library(os)).

p :-
    sleep(0),
    write(p), nl,
    p.
```

Tau Prolog allows you to create a sandbox that sleeps every x inferences, but it doesn't by default because that delays execution.

**Comment by jariazavalverde** [comment]
Added. You only have to uncheck the `stop` option (the limit of inferences is still necessary).

![imagen](https://user-images.githubusercontent.com/5055295/153087329-8ba10335-2495-41e8-867b-e9d3d73559c4.png)

You can check the option while running to stop the execution in the next limit of inferences.

**Comment by Jean-Luc-Picard-2021** [comment]
Ok, interesting, you can als cancel, by checking stop again.
But what is a good limit value? The default 10000 seems a 
little too high, the GUI feels jiggy.

**Comment by jariazavalverde** [comment]
It depends on the browser and the program. Something like 1000 should be fine, but it's a matter of testing I guess.  (Note that you have to reconsult after setting the limit).

**Comment by Jean-Luc-Picard-2021** [comment]
Strange I have hit some browser incompatibility, on MacOSX.

The new feature works in Seamonkey:

<img width="825" alt="Bildschirmfoto 2022-02-09 um 00 18 54" src="https://user-images.githubusercontent.com/95891213/153091991-25d64b52-6818-47c5-8a84-857c78394266.png">

It does not work in Chrome:

<img width="825" alt="Bildschirmfoto 2022-02-09 um 00 18 08" src="https://user-images.githubusercontent.com/95891213/153092005-1fbdfa5c-9d75-4e01-a3c6-d1642dfad97c.png">

**Comment by jariazavalverde** [comment]
> It does not work in Chrome:

That is probably due to the browser cache. Refresh with Cntrl+F5 or clear the cache.

**Comment by Jean-Luc-Picard-2021** [comment]
Will check the browser later again.

I always admire Steve Jobs, how he introduced the MacIntosh
with a mouse that only had one button. Those times there were
mouses with 3 buttons.

So currently trying to figure out what a good GUI would be.
I cannot speak for Tau Prolog. But in my system Limit is a 
system resource, that the end-user has nothing

to do with. It is planned that for non-blocking via some 
auto-tuning the optimal value is found. Browsers have 
a certain affinity to 60 frames per second.(*)

Not yet sure how this turns out. For the control buttons,
I am rather think of something else. Don't know yet what.
Was just having a look at SWISH, it shows me an animation

and an abort button:

<img width="597" alt="Bildschirmfoto 2022-02-09 um 01 06 45" src="https://user-images.githubusercontent.com/95891213/153097037-1016aa9d-57c6-44c7-863f-5ab51dbf0702.png">

after a while it shows stats:

<img width="597" alt="Bildschirmfoto 2022-02-09 um 01 08 03" src="https://user-images.githubusercontent.com/95891213/153097052-ea3d3595-382c-4d7b-9dff-121af4f95750.png">

the abort button shows again after redo:

<img width="597" alt="Bildschirmfoto 2022-02-09 um 01 09 23" src="https://user-images.githubusercontent.com/95891213/153097071-7ed8bca4-a339-4366-9021-106323bbf337.png">

(*)
I found some docu about that. A browser might also updrade
or downgrade the frequency. There is also something related
to animation, called requestAnimationFrame(), but this is

probably not needed for DOM updates.

**Comment by Jean-Luc-Picard-2021** [comment]
You can check here, but a monitor might have more Hz:

https://www.testufo.com/animation-time-graph
<img width="870" alt="Bildschirmfoto 2022-02-09 um 01 25 03" src="https://user-images.githubusercontent.com/95891213/153098706-b4077c70-e656-464a-a60f-1eb8bc71311c.png">
