### ISSUE TITLE
Consider indent through write/1

### ISSUE THREAD

**Issue by ghost** [tau-prolog/sandbox#8]
Hi,

I tried code that does indent through write, by
adding spaces in front of the text. But it didn't work.

<img width="622" alt="Bildschirmfoto 2020-09-27 um 11 56 36" src="https://user-images.githubusercontent.com/5411487/94362022-bb392900-00b8-11eb-8cfe-f5afbe374445.png">

Was more expecting as output display:

```
abc
  def
ghi
```

Bye

**Comment by jariazavalverde** [comment]
Done! Thanks for your suggestion.

![indent](https://user-images.githubusercontent.com/5055295/95568821-fcb8c500-0a24-11eb-82fb-01900d887ee5.PNG)
